<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,21,1,'5pa95bel5YWs5Y+4');
$cfg_Cs[2]=array(0,2,1,'6KOF5L+u5bu65p2Q');
$cfg_Cs[3]=array(2,2,1,'5qmx5p+c');
$cfg_Cs[4]=array(3,2,1,'5b+X6YKm');
$cfg_Cs[5]=array(0,18,1,'6K6+6K6h5biI');
$cfg_Cs[6]=array(2,2,1,'6Zeo56qX');
$cfg_Cs[7]=array(6,2,1,'Q1JH');
$cfg_Cs[8]=array(3,2,1,'5pif6Im65rip5bq3');
$cfg_Cs[9]=array(5,18,1,'6K6+6K6h5biIMQ==');
$cfg_Cs[10]=array(5,18,1,'6K6+6K6h5biIMg==');
$cfg_Cs[11]=array(0,1,1,'572R56uZ5YWs5ZGK');
$cfg_Cs[12]=array(0,20,1,'55uR55CG5YWs5Y+4');
$cfg_Cs[15]=array(0,21,1,'6KOF5L+u5a2m5aCC');
?>