<?php
$z[0]=Array("field","",163,191);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",193,222);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\n                                        <ul class=\"remen_pinpai\">\n                                            <li>\n                                                <a target=\"_blank\" href=\"[field:typelink/]\" class=\"menu_link_ga\">[field:typename/]</a>\n                                            </li>\n                                            <!-- <li>|</li>-->\n                                        </ul>\n										",569,1042);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>