<li>
                        	<dl>
                            	<dt class="sc_lb_list_pic"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="151" height="151" alt="field:title function='html2text(@me)'/]"/></a></dt>
                                <dd>
                                	<a href="[field:arcurl/]" class="shangpin_mc">[field:title/]</a>
                                </dd>
                            </dl>
                        </li>