<field:zuopinming itemname="作品名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zuopinming>
<field:shejishi itemname="设计师" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="徐晓婷,陈伟,庄焕阳,经飞,包国俊,欧度,实习设计师"  maxlength="" page="">
</field:shejishi>

<field:fengge itemname="风格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fengge>
<field:huxing itemname="户型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:huxing>
<field:zuopinjieshao itemname="作品介绍" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zuopinjieshao>
<field:zuopintupian itemname="作品图片" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zuopintupian>
<field:touxiang itemname="设计师头像" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:touxiang>
<field:shejishiming itemname="设计师名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shejishiming>
<field:shoufeibiaozhun itemname="收费标准" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shoufeibiaozhun>123
<field:oicq itemname="QQ" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:oicq>
<field:dianziyouxiang itemname="Email" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dianziyouxiang>
<field:dianhua itemname="电话" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dianhua>
<field:shejilinian itemname="设计理念" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:shejilinian>
<field:zuopinrongyu itemname="作品荣誉" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zuopinrongyu>
<field:zhuyaozuopin itemname="主要作品" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zhuyaozuopin>