<channel:id>18</channel:id>
<channel:nid>anlizhanshi</channel:nid>
<channel:typename>案例展示</channel:typename>
<channel:maintable>cake_archives</channel:maintable>
<channel:addtable>cake_anlizhanshi</channel:addtable>
<channel:addcon>archives_add.php</channel:addcon>
<channel:mancon>content_list.php</channel:mancon>
<channel:editcon>archives_edit.php</channel:editcon>
<channel:useraddcon>archives_add.php</channel:useraddcon>
<channel:usermancon>content_list.php</channel:usermancon>
<channel:usereditcon>archives_edit.php</channel:usereditcon>
<channel:fieldset>
<field:zuopinming itemname="作品名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zuopinming>
<field:shejishi itemname="设计师" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="徐春龙,郭瑞,宋玉,吴彩霞,包国俊,实习设计师"  maxlength="" page="">
</field:shejishi>
<field:fengge itemname="风格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:fengge>
<field:huxing itemname="户型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:huxing>
<field:zuopinjieshao itemname="作品介绍" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zuopinjieshao>
<field:zuopintupian itemname="作品图片" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zuopintupian>
<field:touxiang itemname="设计师头像" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:touxiang>
<field:shejishiming itemname="设计师名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shejishiming>
<field:shoufeibiaozhun itemname="收费标准" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shoufeibiaozhun>123
<field:oicq itemname="QQ" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:oicq>
<field:dianziyouxiang itemname="Email" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dianziyouxiang>
<field:dianhua itemname="电话" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dianhua>
<field:shejilinian itemname="设计理念" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:shejilinian>
<field:zuopinrongyu itemname="作品荣誉" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zuopinrongyu>
<field:zhuyaozuopin itemname="主要作品" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="6000" page="">
</field:zhuyaozuopin>
</channel:fieldset>
<channel:listfields>zuopinming,shejishi,fengge,huxing,zuopinjieshao,zuopintupian,touxiang,shejishiming,shoufeibiaozhun,oicq,dianziyouxiang,dianhua,shejilinian,zuopinrongyu,zhuyaozuopin</channel:listfields>
<channel:allfields></channel:allfields>
<channel:issystem>0</channel:issystem>
<channel:isshow>1</channel:isshow>
<channel:issend>0</channel:issend>
<channel:arcsta>-1</channel:arcsta>
<channel:usertype></channel:usertype>
<channel:sendrank>0</channel:sendrank>
<channel:isdefault>0</channel:isdefault>
<channel:needdes>1</channel:needdes>
<channel:needpic>1</channel:needpic>
<channel:titlename>标题</channel:titlename>
<channel:onlyone>0</channel:onlyone>
<channel:dfcid>0</channel:dfcid>
