
                                        <ul class="remen_pinpai">
                                            <li>
                                                <a target="_blank" href="[field:typelink/]" class="menu_link_ga">[field:typename/]</a>
                                            </li>
                                            <!-- <li>|</li>-->
                                        </ul>
										