<?php
$z[0]=Array("global","",1021,1045);
$z[0][4]['name']="cfg_phone";
$z[1]=Array("cfg_indexurl","",1232,1252);
$z[2]=Array("global","",1264,1296);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("cfg_indexurl","",1647,1667);
$z[4]=Array("channel","\n                    <li class=\"dht_4\"><a href=\"[field:typeurl/]\" class=\"dht_link1\">[field:typename/]</a></li>\n					",2708,2873);
$z[4][4]['type']="top";
$z[4][4]['row']="10";

?>