<?php
$z[0]=Array("arclist","\n								<a href='[field:arcurl/]' target='_blank'><img src='[field:litpic/]' width='492' height='270'></a> \n								",886,1087);
$z[0][4]['typeid']="2";
$z[0][4]['flag']="c";
$z[0][4]['row']="5";
$z[0][4]['orderby']="id";
$z[0][4]['type']="image";
$z[1]=Array("arclist","\n						    <li><a href=\"[field:arcurl /]\" target=\"_blank\" class=\"shangpin_mc\">[field:title /]</a></li>\n						    ",2688,2865);
$z[1][4]['titlelen']="40";
$z[1][4]['row']="10";
$z[1][4]['typeid']="11";

?>